UBUNTU: SAUCE: Revert selftests/ "bpf: Zero-fill re-used per-cpu map element"
BugLink: https://bugs.launchpad.net/bugs/1906866

This PARTIALLY reverts commit d946d4ddd6af531398201e7ce8f73bd1d8a98e2a,
so as to keep the bpf kernel code change introduced by the upstream
commit, but omit the uncompilable (in v5.4) new test case.

Reported upstream:
 https://lore.kernel.org/stable/20201204182846.27110-1-kamal@canonical.com/T/#u

This v5.4.78 commit breaks the tools/testing/selftests/bpf build:

[linux-5.4.y] c602ad2b52dc bpf: Zero-fill re-used per-cpu map element
[focal] d946d4ddd6af bpf: Zero-fill re-used per-cpu map element

Like this:

        prog_tests/map_init.c:5:10: fatal error: test_map_init.skel.h:
No such file or directory
            5 | #include "test_map_init.skel.h"

Because tools/testing/selftests/bpf/Makefile in v5.4 does not have the
"skeleton header generation" stuff (circa v5.6).

Signed-off-by: Kamal Mostafa <kamal@canonical.com>
Acked-by: Kleber Sacilotto de Souza <kleber.souza@canonical.com>
Acked-by: Colin King <colin.king@canonical.com>
Signed-off-by: Stefan Bader <stefan.bader@canonical.com>